/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IMSProjectForms;

import static IMSProjectForms.SalesPerson.ItemStockPurchase;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AmeerHamza
 */
public class SalesForm extends javax.swing.JFrame {

    /**
     * Creates new form SalesForm
     */
    public SalesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemIdG = new javax.swing.JLabel();
        ItemNameG = new javax.swing.JLabel();
        CategoryG = new javax.swing.JLabel();
        QuantityGet = new javax.swing.JTextField();
        PriceGet = new javax.swing.JTextField();
        Submit = new javax.swing.JLabel();
        BackImageLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ItemIdG, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 90, 120, 20));
        getContentPane().add(ItemNameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 125, 120, 20));
        getContentPane().add(CategoryG, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 158, 120, 20));

        QuantityGet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuantityGetMousePressed(evt);
            }
        });
        QuantityGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityGetActionPerformed(evt);
            }
        });
        QuantityGet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityGetKeyTyped(evt);
            }
        });
        getContentPane().add(QuantityGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 187, 130, 29));
        getContentPane().add(PriceGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 221, 130, 29));

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SubmitDefault.png"))); // NOI18N
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 248, -1, 60));

        BackImageLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SalesForm.jpg"))); // NOI18N
        getContentPane().add(BackImageLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 275, 314));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
        
       try{
        
          int row = SalesPerson.ItemStockPurchase.getSelectedRow();
          
          SalesPerson.ItemStockPurchase.getValueAt(row, 0);
          SalesPerson.ItemStockPurchase.getValueAt(row, 1);
          SalesPerson.ItemStockPurchase.getValueAt(row, 2);
          SalesPerson.ItemStockPurchase.getValueAt(row, 3);
          SalesPerson.ItemStockPurchase.getValueAt(row, 4);

          
          ItemIdG.setText((String) SalesPerson.ItemStockPurchase.getValueAt(row, 0));
          ItemNameG.setText((String) SalesPerson.ItemStockPurchase.getValueAt(row, 1));
          CategoryG.setText((String) SalesPerson.ItemStockPurchase.getValueAt(row, 2));
         
          
          int IDG =Integer.parseInt(ItemIdG.getText());
          String NameG = ItemNameG.getText();
          String CategoryGet = CategoryG.getText();
          int Quantity =Integer.parseInt(QuantityGet.getText());
          int Price =  Integer.parseInt(PriceGet.getText());;
          int QuantityMinus;
          int QuantityPlus;
          
             QuantityMinus = Integer.parseInt(QuantityGet.getText());
             Connections.st.executeUpdate(" Update Items set Quantity = Quantity - "+QuantityMinus+" where  ID  = "+IDG+" ");
            
             QuantityPlus = Integer.parseInt(QuantityGet.getText());
             Connections.st.executeUpdate(" Update Items set Sold = Sold + "+QuantityPlus+" where  ID  = "+IDG+" ");
           
             Connections.st.executeUpdate("insert into Invoice values("+IDG+",'"+NameG+"','"+CategoryGet+"',"+Quantity+","+Price+")");
           
            int PriceSet = Quantity * Price;
            
            
            JOptionPane.showMessageDialog(this,"Bill Created Successfully");
            
          
        } catch (SQLException ex) {
            Logger.getLogger(SalesPerson.class.getName()).log(Level.SEVERE, null, ex);
        
        
        
         DefaultTableModel dtm;
        ResultSetMetaData  rsmd;
        String str = "Select * from Invoice";
        try{
            Connections.Connections();
            Connections.st = Connections.cn.createStatement();
            ResultSet rs = Connections.st.executeQuery(str);

            rsmd = rs.getMetaData();
            int column = rsmd.getColumnCount();
            dtm = new DefaultTableModel();
            Vector column_name = new Vector();
            Vector row_data = new Vector();
            for(int i = 1; i<=column; i++){
                column_name.addElement(rsmd.getColumnName(i));
            }
            dtm.setColumnIdentifiers(column_name);
            while(rs.next()){
                row_data = new Vector();
                for(int j =1;j<=column;j++){
                    row_data.addElement(rs.getString(j));
                }
                dtm.addRow(row_data);
            }
            SalesPerson.InvoiceTbl.setModel(dtm);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }}
       this.dispose();
       
         DefaultTableModel dtm;
        ResultSetMetaData  rsmd;
        String str = "Select * from items";
        try{
            Connections.Connections();
            Connections.st = Connections.cn.createStatement();
            ResultSet rs = Connections.st.executeQuery(str);

            rsmd = rs.getMetaData();
            int column = rsmd.getColumnCount();
            dtm = new DefaultTableModel();
            Vector column_name = new Vector();
            Vector row_data = new Vector();
            for(int i = 1; i<=column; i++){
                column_name.addElement(rsmd.getColumnName(i));
            }
            dtm.setColumnIdentifiers(column_name);
            while(rs.next()){
                row_data = new Vector();
                for(int j =1;j<=column;j++){
                    row_data.addElement(rs.getString(j));
                }
                dtm.addRow(row_data);
            }
            ItemStockPurchase.setModel(dtm);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       

    }//GEN-LAST:event_SubmitMouseClicked

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/SubmitOver.png"));
        Submit.setIcon(II);
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/SubmitDefault.png"));
        Submit.setIcon(II);
    }//GEN-LAST:event_SubmitMouseExited

    private void SubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/SubmitClick.png"));
        Submit.setIcon(II);

    }//GEN-LAST:event_SubmitMousePressed

    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/SubmitOver.png"));
        Submit.setIcon(II);
    }//GEN-LAST:event_SubmitMouseReleased

    private void QuantityGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityGetActionPerformed
        // TODO add your handling code here:
        
        try {
            int IDG =Integer.parseInt(ItemIdG.getText());
            
            Connections.Connections();
            
            
            

            ResultSet rs =Connections.st.executeQuery("select Price from items where ID="+IDG+" ");
            int num=0;
            while(rs.next())
            {
                num=rs.getInt("Price");
            
                
            }
            
           
        int quantity=Integer.parseInt(QuantityGet.getText());
        
      

        int totalp=num*quantity;
        PriceGet.setText(totalp+"");

        } catch (SQLException ex) {
            Logger.getLogger(SalesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }//GEN-LAST:event_QuantityGetActionPerformed

    private void QuantityGetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityGetKeyTyped
 
//        try {
//            int IDG =Integer.parseInt(ItemIdG.getText());
//            
//            Connections.Connections();
//            
//            
//            
//
//            ResultSet rs =Connections.st.executeQuery("select Price from items where ID="+IDG+" ");
//            int num=0;
//            while(rs.next())
//            {
//                num=rs.getInt("Price");
//            
//                
//            }
//            
//           
//        int quantity=Integer.parseInt(QuantityGet.getText());
//        
//        JOptionPane.showMessageDialog(null, num+"");
//
//      //  int totalp=num*quantity;
//       // PriceGet.setText(totalp+"");
//      //  JOptionPane.showMessageDialog(null, totalp+"");
//        } catch (SQLException ex) {
//            Logger.getLogger(SalesForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_QuantityGetKeyTyped

    private void QuantityGetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityGetMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_QuantityGetMousePressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackImageLable;
    public static javax.swing.JLabel CategoryG;
    public static javax.swing.JLabel ItemIdG;
    public static javax.swing.JLabel ItemNameG;
    private javax.swing.JTextField PriceGet;
    public static javax.swing.JTextField QuantityGet;
    public static javax.swing.JLabel Submit;
    // End of variables declaration//GEN-END:variables
}
